use crate::bundle::{BundleFormatVersion, BundleHeader, IndexEntry};
use crate::integrity::{IntegrityAlgorithm, IntegrityPolicy};
use crate::protocol::{HostnameSegment, HttpMethod, PathResolver};
use crate::remote::{ListRemoteBundleInfo, RemoteBundleInfo};
use crate::signature::{SignatureAlgorithm, VerifyingKeyFormat};
use crate::source::{
  BundleManifestMetadata, BundleSourceType, BundleSourceVerifyMode, BundleSourceVersion,
  ListBundleItem,
};
use crate::updater::BundleUpdateInfo;
use specta::TypeCollection;
use specta_typescript::Typescript;
use std::path::PathBuf;

#[test]
fn export_bindings() {
  let mut types = TypeCollection::default();
  types.register::<IntegrityAlgorithm>();
  types.register::<IntegrityPolicy>();
  types.register::<BundleSourceVerifyMode>();
  types.register::<BundleSourceType>();
  types.register::<SignatureAlgorithm>();
  types.register::<VerifyingKeyFormat>();
  types.register::<HostnameSegment>();
  types.register::<PathResolver>();
  types.register::<HttpMethod>();
  types.register::<ListRemoteBundleInfo>();
  types.register::<RemoteBundleInfo>();
  types.register::<BundleManifestMetadata>();
  types.register::<BundleSourceVersion>();
  types.register::<ListBundleItem>();
  types.register::<BundleUpdateInfo>();
  types.register::<BundleFormatVersion>();
  types.register::<BundleHeader>();
  types.register::<IndexEntry>();

  let body = Typescript::default()
    .export(&types)
    .expect("failed to export TypeScript bindings");
  let rendered = format!(
    "// @generated from `src/*.rs` by `cargo test` — do not edit.\n{}",
    body
      .strip_prefix("// This file has been generated by Specta. DO NOT EDIT.\n\n")
      .unwrap_or(&body)
  );

  let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("lib/bindings.ts");
  if std::fs::read_to_string(&path).ok().as_deref() != Some(rendered.as_str()) {
    std::fs::write(&path, &rendered)
      .unwrap_or_else(|e| panic!("failed to write {}: {e}", path.display()));
  }
}
