// The single source of truth for every error code this binding exposes. Included by `src/error.rs`
// (→ the `ErrorCode` enum) and by `build.rs` (→ `lib/error-codes.ts`), each expanding it with its
// own `error_codes!`. Add a code here and both sides follow.
error_codes! {
  CoreIo => "core.io",
  CoreCompress => "core.compress",
  CoreDecompress => "core.decompress",
  CoreEncode => "core.encode",
  CoreDecode => "core.decode",
  CoreHttp => "core.http",
  CoreHttpInvalidUri => "core.http_invalid_uri",
  CoreCancelled => "core.cancelled",
  CoreTimeout => "core.timeout",
  CoreInvalidMagicNum => "core.invalid_magic_num",
  CoreInvalidVersion => "core.invalid_version",
  CoreInvalidHeaderChecksum => "core.invalid_header_checksum",
  CoreInvalidIndexChecksum => "core.invalid_index_checksum",
  CoreChecksumMismatch => "core.checksum_mismatch",
  CoreBundleNotFound => "core.bundle_not_found",
  CoreInvalidFilepath => "core.invalid_filepath",
  CoreSerdeJson => "core.serde_json",
  CoreCannotResolveProxyServer => "core.cannot_resolve_proxy_server",
  CoreHttpClient => "core.http_client",
  CoreRemoteHttp => "core.remote_http",
  CoreBadRemoteResponse => "core.bad_remote_response",
  CoreInvalidRemoteConfig => "core.invalid_remote_config",
  CoreInvalidUpdaterConfig => "core.invalid_updater_config",
  CoreInvalidIntegrity => "core.invalid_integrity",
  CoreIntegrityRequired => "core.integrity_required",
  CoreIntegrityVerifyFailed => "core.integrity_verify_failed",
  CoreInvalidSignature => "core.invalid_signature",
  CoreInvalidSignatureKey => "core.invalid_signature_key",
  CoreExpectSignatureNotFound => "core.expect_signature_not_found",
  CoreSignatureVerifyFailed => "core.signature_verify_failed",
  CoreGeneric => "core.generic",
  InvalidMethod => "invalid_method",
  InvalidRequest => "invalid_request",
  InvalidSignatureKey => "invalid_signature_key",
  NullHandle => "null_handle",
  /// Raised in `lib/*.ts`: a handle constructor returned null, or an error payload carried no code.
  #[allow(dead_code, reason = "TypeScript-side code; declared here to reach `ErrorCode`")]
  Unknown => "unknown",
}
