enableGlobalCache: true

nodeLinker: node-modules

preferReuse: true

supportedArchitectures:
  cpu:
    - x64
    - ia32
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.12.0.cjs

catalog:
  "@types/node": "22.19.3"
  vitest: "4.0.15"
  typescript: "5.9.3"
  tsdown: "0.20.1"

npmAuditRegistry: "https://registry.npmjs.org"

packageExtensions:
  "@cloudflare/kumo@2.0.2":
    peerDependenciesMeta:
      echarts:
        optional: true
