approvedGitRepositories:
  - "**"

catalog:
  "@types/node": 25.9.1
  tsdown: 0.22.13
  typescript: 7.0.2
  vitest: 4.1.8

enableGlobalCache: true

enableScripts: true

enableTransparentWorkspaces: false

logFilters:
  - level: discard
    pattern: "typescript is listed by your project with version 7.0.2 (*), which doesn't satisfy what @pulumi/pulumi and other dependencies request"

nodeLinker: node-modules

npmAuditRegistry: "https://registry.npmjs.org"

npmMinimalAgeGate: 0m

npmPreapprovedPackages:
  - "@wvb/*"
  - "@wvb-playground/*"

preferReuse: true

supportedArchitectures:
  cpu:
    - x64
    - ia32
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.18.0.cjs
