/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A complete bundle including metadata and file data.
 *
 * Represents a `.wvb` bundle file loaded entirely into memory.
 * Use this when you need to access multiple files or build new bundles.
 *
 * @example
 * ```typescript
 * // Read a bundle from file
 * const bundle = await readBundle('app.wvb');
 *
 * // Access files
 * const html = bundle.getData('/index.html');
 * if (html) {
 *   console.log(html.toString('utf-8'));
 * }
 * ```
 */
export declare class Bundle {
  /**
   * Returns the bundle descriptor (header and index).
   *
   * @returns {BundleDescriptor} Bundle metadata
   *
   * @example
   * ```typescript
   * const descriptor = bundle.descriptor();
   * const index = descriptor.index();
   * ```
   */
  descriptor(): BundleDescriptor
  /**
   * Retrieves file data by path.
   *
   * Returns the decompressed file contents, or null if the path doesn't exist.
   *
   * @param {string} path - File path in the bundle (e.g., "/index.html")
   * @returns {Buffer | null} File contents or null if not found
   *
   * @example
   * ```typescript
   * const data = bundle.getData('/index.html');
   * if (data) {
   *   console.log(data.toString('utf-8'));
   * }
   * ```
   */
  getData(path: string): Buffer | null
  /**
   * Retrieves the checksum of file data by path.
   *
   * @param {string} path - File path in the bundle
   * @returns {number | null} xxHash-32 checksum or null if not found
   */
  getDataChecksum(path: string): number | null
}

/**
 * Builder for creating bundle files.
 *
 * Allows you to add files, set options, and generate a complete bundle.
 *
 * @example
 * ```typescript
 * const builder = new BundleBuilder();
 *
 * // Add files
 * builder.insertEntry('/index.html', Buffer.from('<html>...</html>'));
 * builder.insertEntry('/app.js', Buffer.from("console.log('hello');"));
 *
 * // Build the bundle
 * const bundle = builder.build();
 *
 * // Write to file
 * await writeBundle(bundle, 'app.wvb');
 * ```
 */
export declare class BundleBuilder {
  /**
   * Creates a new bundle builder.
   *
   * @param {Version} [version] - Bundle format version (defaults to V1)
   *
   * @example
   * ```typescript
   * const builder = new BundleBuilder();
   * ```
   */
  constructor(version?: Version | undefined | null)
  /**
   * Gets the bundle format version.
   *
   * @returns {Version} Bundle format version
   */
  get version(): Version
  /**
   * Returns all entry paths currently in the builder.
   *
   * @returns {string[]} Array of file paths
   *
   * @example
   * ```typescript
   * const paths = builder.entryPaths();
   * console.log(paths); // ["/index.html", "/app.js"]
   * ```
   */
  entryPaths(): Array<string>
  /**
   * Adds or updates a file in the bundle.
   *
   * If `contentType` is not provided, it will be auto-detected from the file
   * extension and content.
   *
   * @param {string} path - File path (must start with "/")
   * @param {Buffer} data - File contents
   * @param {string} [contentType] - MIME type (auto-detected if not provided)
   * @param {Record<string, string>} [headers] - Optional HTTP headers
   * @returns {boolean} True if a file was replaced, false if newly added
   *
   * @example
   * ```typescript
   * // Auto-detect MIME type
   * builder.insertEntry('/index.html', Buffer.from('<html></html>'));
   *
   * // Specify MIME type
   * builder.insertEntry('/data.bin', buffer, 'application/octet-stream');
   *
   * // With custom headers
   * builder.insertEntry('/style.css', cssBuffer, 'text/css', {
   *   'Cache-Control': 'max-age=3600',
   * });
   * ```
   */
  insertEntry(path: string, data: Buffer, contentType?: string | undefined | null, headers?: Record<string, string> | undefined | null): boolean
  /**
   * Removes a file from the bundle.
   *
   * @param {string} path - File path to remove
   * @returns {boolean} True if the file was removed, false if not found
   *
   * @example
   * ```typescript
   * builder.removeEntry('/old-file.js');
   * ```
   */
  removeEntry(path: string): boolean
  /**
   * Checks if a file path exists in the builder.
   *
   * @param {string} path - File path to check
   * @returns {boolean} True if the path exists
   *
   * @example
   * ```typescript
   * if (builder.containsEntry('/index.html')) {
   *   console.log('index.html already added');
   * }
   * ```
   */
  containsEntry(path: string): boolean
  /**
   * Builds the bundle with all added files.
   *
   * This consumes the builder's entries and creates a complete bundle with
   * compressed data.
   *
   * @param {BundleBuilderOptions} [options] - Build options
   * @returns {Bundle} The built bundle
   *
   * @example
   * ```typescript
   * const bundle = builder.build();
   * await writeBundle(bundle, 'output.wvb');
   * ```
   */
  build(options?: BundleBuilderOptions | undefined | null): Bundle
}

/**
 * Bundle metadata including header and index information.
 *
 * A descriptor contains only the metadata without loading the actual file data,
 * making it efficient for inspecting bundle contents.
 *
 * @example
 * ```typescript
 * const bundle = await readBundle('app.wvb');
 * const descriptor = bundle.descriptor();
 * const header = descriptor.header();
 * const index = descriptor.index();
 * ```
 */
export declare class BundleDescriptor {
  /**
   * Returns the bundle header.
   *
   * @returns {Header} Bundle header with format metadata
   */
  header(): Header
  /**
   * Returns the bundle index.
   *
   * @returns {Index} Bundle index with file metadata
   */
  index(): Index
  /**
   * Read data from the bundle.
   *
   * @param {string} filepath - File path for the bundle
   * @param {string} path - Path to the bundle data
   * @returns {Buffer | null} Data from the bundle or `null` if not found
   */
  getData(filepath: string, path: string): Buffer | null
  /**
   * Read checksum from the bundle.
   *
   * @param {string} filepath - File path for the bundle
   * @param {string} path - Path to the bundle data
   * @returns {number | null} Checksum for the bundle data or `null` if not found
   */
  getDataChecksum(filepath: string, path: string): number | null
  /**
   * Asynchronously read data from the bundle.
   *
   * @param {string} filepath - File path for the bundle
   * @param {string} path - Path to the bundle data
   * @returns {Promise<Buffer | null>} Data from the bundle or `null` if not found
   */
  asyncGetData(filepath: string, path: string): Promise<Buffer | null>
  /**
   * Asynchronously read checksum from the bundle.
   *
   * @param {string} filepath - File path for the bundle
   * @param {string} path - Path to the bundle data
   * @returns {Promise<number | null>} Checksum for the bundle data or `null` if not found
   */
  asyncGetDataChecksum(filepath: string, path: string): Promise<number | null>
}

/**
 * Protocol handler for serving files from bundle sources.
 *
 * Serves web resources from `.wvb` bundle files, supporting:
 * - GET and HEAD HTTP methods
 * - HTTP Range requests for streaming
 * - Content-Type and custom HTTP headers
 *
 * @example
 * ```typescript
 * const source = new Source({
 *   builtinDir: './bundles/builtin',
 *   remoteDir: './bundles/remote',
 * });
 *
 * const protocol = new BundleProtocol(source);
 *
 * // Handle a request
 * const response = await protocol.handle('get', 'bundle://app/index.html');
 * console.log(`Status: ${response.status}`);
 * console.log(`Content-Type: ${response.headers['content-type']}`);
 * ```
 */
export declare class BundleProtocol {
  /**
   * Creates a new bundle protocol handler.
   *
   * @param {Source} source - Bundle source to serve files from
   * @param {BundleProtocolOptions} [options] - How the request uri is resolved
   *
   * @example
   * ```typescript
   * const source = new Source({
   *   builtinDir: './bundles',
   *   remoteDir: './remote',
   * });
   * const protocol = new BundleProtocol(source);
   * ```
   *
   * @example
   * ```typescript
   * // `https://cdn.example.com/my-app/about` -> "/about/index.html" of the "my-app" bundle
   * const protocol = new BundleProtocol(source, {
   *   bundleResolver: { type: 'pathname' },
   * });
   * ```
   *
   * @example
   * ```typescript
   * // Entry checksum verification is inherited from the source's read options; to serve
   * // without checking entry checksums, configure it on the source instead.
   * const source = new Source({
   *   builtinDir: './bundles',
   *   remoteDir: './remote',
   *   options: { dataRead: { checksum: { verify: false } } },
   * });
   * const protocol = new BundleProtocol(source);
   * ```
   */
  constructor(source: Source, options?: BundleProtocolOptions | undefined | null)
  /**
   * Handles an HTTP request and returns a response.
   *
   * Processes requests in the format `scheme://bundle_name/path/to/file`.
   *
   * @param {HttpMethod} method - HTTP method (GET or HEAD)
   * @param {string} uri - Request URI (e.g., "bundle://app/index.html")
   * @param {Record<string, string>} [headers] - Optional request headers
   * @param {Buffer} [body] - Optional request body (accepted, but unused: only GET/HEAD are served)
   * @returns {Promise<HttpResponse>} HTTP response
   *
   * @example
   * ```typescript
   * // GET request
   * const response = await protocol.handle('get', 'bundle://app/index.html');
   * if (response.status === 200) {
   *   console.log(response.body.toString('utf-8'));
   * }
   * ```
   *
   * @example
   * ```typescript
   * // Range request for streaming
   * const response = await protocol.handle('get', 'bundle://app/video.mp4', { Range: 'bytes=0-1023' });
   * console.log(`Status: ${response.status}`); // 206 Partial Content
   * ```
   */
  handle(method: HttpMethod, uri: string, headers?: Record<string, string> | undefined | null, body?: Buffer | undefined | null): Promise<HttpResponse>
}

export declare class Cancellation {
  constructor()
  cancel(): void
  isCancelled(): boolean
}

/**
 * Bundle header containing format metadata.
 *
 * The header is the first 17 bytes of a `.wvb` file and includes:
 * - Magic number (🌐🎁)
 * - Format version
 * - Index size
 * - Header checksum
 */
export declare class Header {
  /**
   * Returns the bundle format version.
   *
   * @returns {Version} The format version (e.g., V1)
   *
   * @example
   * ```typescript
   * const header = bundle.descriptor().header();
   * console.log(header.version()); // 'v1'
   * ```
   */
  version(): Version
  /**
   * Returns the byte offset where the index section ends.
   *
   * This marks the start of the data section.
   *
   * @returns {bigint} Byte offset
   */
  indexEndOffset(): bigint
  /**
   * Returns the size of the index section in bytes.
   *
   * @returns {number} Index size in bytes
   */
  indexSize(): number
}

/**
 * Bundle index mapping file paths to their metadata.
 *
 * The index is stored as binary data in the bundle file and maps file paths
 * to their metadata (offset, length, content-type, headers, etc.).
 */
export declare class Index {
  /**
   * Returns all index entries as a map of path to metadata.
   *
   * @returns {Record<string, IndexEntry>} Map of file paths to entry metadata
   *
   * @example
   * ```typescript
   * const index = bundle.descriptor().index();
   * const entries = index.entries();
   * for (const [path, entry] of Object.entries(entries)) {
   *   console.log(`${path}: ${entry.contentType}`);
   * }
   * ```
   */
  entries(): Record<string, IndexEntry>
  /**
   * Gets the index entry for a specific file path.
   *
   * @param {string} path - File path in the bundle (e.g., "/index.html")
   * @returns {IndexEntry | null} Entry metadata or null if not found
   *
   * @example
   * ```typescript
   * const entry = index.getEntry('/index.html');
   * if (entry) {
   *   console.log(`Content-Type: ${entry.contentType}`);
   * }
   * ```
   */
  getEntry(path: string): IndexEntry | null
  /**
   * Checks if a file path exists in the bundle.
   *
   * @param {string} path - File path to check
   * @returns {boolean} True if the path exists
   *
   * @example
   * ```typescript
   * if (index.containsPath('/app.js')) {
   *   console.log('app.js is in the bundle');
   * }
   * ```
   */
  containsPath(path: string): boolean
}

/**
 * A digest over some bytes, serialized as `<algorithm>:<base64>` (e.g. `"sha256:n4bQ..."`).
 *
 * Created by [`computeIntegrity`] or [`parseIntegrity`].
 */
export declare class Integrity {
  /**
   * The raw digest bytes.
   *
   * @returns {Buffer} The digest
   */
  value(): Buffer
  /**
   * Whether `data` digests to this integrity.
   *
   * @param {Buffer} data - Bytes to check
   * @returns {boolean} `true` when the bytes match
   */
  validate(data: Buffer): boolean
  /**
   * Serializes to `<algorithm>:<base64>`.
   *
   * @returns {string} The serialized integrity string
   */
  serialize(): string
}

export declare class LoadedDescriptor {
  descriptor(): BundleDescriptor
  getData(path: string): Promise<Buffer | null>
  getDataChecksum(path: string): Promise<number | null>
}

/**
 * Protocol handler that proxies requests to other servers.
 *
 * Forwards requests to local development servers for hot-reloading workflows.
 *
 * @example
 * ```typescript
 * const protocol = new ProxyProtocol({
 *   myapp: 'http://localhost:3000',
 *   api: 'http://localhost:8080',
 * });
 *
 * // This proxies to http://localhost:3000/index.html
 * const response = await protocol.handle('get', 'app://myapp/index.html');
 * ```
 */
export declare class ProxyProtocol {
  /**
   * Creates a new proxy protocol handler.
   *
   * The resolver returns the target server for a request uri; the path and query of
   * the request are appended to it. A static host mapping resolves by uri hostname,
   * while a function receives the full uri and returns the target, or `null` to not
   * proxy.
   *
   * @param {Record<string, string> | ((uri: string) => Promise<string | null>)} resolver - Host mapping or custom resolver
   *
   * @example
   * ```typescript
   * const protocol = new ProxyProtocol({
   *   myapp: 'http://localhost:3000',
   *   api: 'http://localhost:8080',
   * });
   * ```
   *
   * @example
   * ```typescript
   * // Proxies `app://myapp/index.html` to `http://localhost:3000/index.html`
   * const protocol = new ProxyProtocol(async uri => {
   *   const port = await lookupDevServer(new URL(uri).hostname);
   *   return port != null ? `http://localhost:${port}` : null;
   * });
   * ```
   */
  constructor(resolver: Record<string, string> | ((uri: string) => Promise<string | null>))
  /**
   * Handles an HTTP request by proxying it to the resolved server.
   *
   * @param {HttpMethod} method - HTTP method
   * @param {string} uri - Request URI (e.g., "app://myapp/api/data")
   * @param {Record<string, string>} [headers] - Optional request headers
   * @param {Buffer} [body] - Optional request body, forwarded as-is (POST/PUT/PATCH)
   * @returns {Promise<HttpResponse>} HTTP response from the proxied server
   *
   * @example
   * ```typescript
   * // Proxies to http://localhost:3000/api/data?foo=bar
   * const response = await protocol.handle('get', 'app://myapp/api/data?foo=bar');
   * console.log(response.status);
   * ```
   *
   * @example
   * ```typescript
   * // POST with a body
   * const response = await protocol.handle(
   *   'post',
   *   'app://api/submit',
   *   { 'Content-Type': 'application/json' },
   *   Buffer.from(JSON.stringify({ hello: 'world' })),
   * );
   * ```
   */
  handle(method: HttpMethod, uri: string, headers?: Record<string, string> | undefined | null, body?: Buffer | undefined | null): Promise<HttpResponse>
}

/**
 * HTTP client for getting updates and downloading bundles from a remote server.
 *
 * @example
 * ```typescript
 * const remote = new Remote({ baseUrl: 'https://updates.example.com' });
 *
 * const response = await remote.getUpdate();
 * if (response != null) {
 *   for (const bundle of response.update.bundles) {
 *     await remote.download(bundle.downloadUrl, `./remote/${bundle.name}/${bundle.version}.wvb`);
 *   }
 * }
 * ```
 */
export declare class Remote {
  /**
   * Creates a new remote client.
   *
   * @param {RemoteConfig} config - Client config
   *
   * @example
   * ```typescript
   * const remote = new Remote({
   *   baseUrl: 'https://updates.example.com',
   *   http: { timeout: 60000 },
   *   onDownload: data => {
   *     const percent = (data.downloadedBytes / data.totalBytes) * 100;
   *     console.log(`Progress: ${percent.toFixed(1)}%`);
   *   },
   * });
   * ```
   */
  constructor(config: RemoteConfig)
  /**
   * Gets update information from the remote server.
   *
   * @param {RemoteGetUpdateOptions} [options] - Request options
   * @returns {Promise<RemoteUpdateResponse | null>} Update response, or null when not modified
   */
  getUpdate(options?: RemoteGetUpdateOptions | undefined | null): Promise<RemoteUpdateResponse | null>
  /**
   * Downloads a bundle into the given file path.
   *
   * @param {string} url - URL to download from
   * @param {string} filepath - Destination file path
   * @param {Cancellation} [cancellation] - Cancels the download when triggered
   */
  download(url: string, filepath: string, cancellation?: Cancellation | undefined | null): Promise<void>
}

export declare class Source {
  constructor(config: SourceConfig)
  listBundles(): Promise<Array<SourceListItem>>
  listBuiltinBundles(): Promise<Array<SourceListItem>>
  listRemoteBundles(): Promise<Array<SourceListItem>>
  getVersion(bundleName: string): Promise<BundleSourceVersion | null>
  getRemoteStagedVersion(bundleName: string): Promise<string | null>
  getRemotePreviousVersion(bundleName: string): Promise<string | null>
  updateRemoteVersion(bundleName: string, version: string): Promise<ManifestSetCurrentVersionResult>
  updateRemoteVersions(items: Record<string, string>): Promise<Array<ManifestSetCurrentVersionResult>>
  stageRemoteBundle(bundleName: string, data: ManifestStageData): Promise<ManifestStageResult>
  stageRemoteBundles(items: Record<string, ManifestStageData>): Promise<Array<ManifestStageResult>>
  resolveFilepath(bundleName: string): Promise<string>
  getBuiltinBundleFilepath(bundleName: string, version: string): string
  getRemoteBundleFilepath(bundleName: string, version: string): string
  fetchBundle(bundleName: string): Promise<Bundle>
  fetchBuiltinBundle(bundleName: string, version: string): Promise<Bundle>
  fetchRemoteBundle(bundleName: string, version: string): Promise<Bundle>
  fetchDescriptor(bundleName: string): Promise<BundleDescriptor>
  getBuiltinVersionData(bundleName: string, version: string): Promise<ManifestVersionData | null>
  getRemoteVersionData(bundleName: string, version: string): Promise<ManifestVersionData | null>
  load(bundleName: string): Promise<LoadedDescriptor>
  unload(bundleName: string): boolean
  removeRemoteBundle(bundleName: string, version: string, force?: boolean | undefined | null): Promise<ManifestRemoveResult>
  removeRemoteBundles(items: Record<string, ManifestRemoveData>): Promise<Array<ManifestRemoveResult>>
  pruneRemoteBundle(bundleName: string): Promise<ManifestPruneResult>
  pruneRemoteBundles(bundleNames: Array<string>): Promise<Array<ManifestPruneResult>>
}

export declare class Updater {
  constructor(source: Source, remote: Remote, updateFilepath: string, options?: UpdaterOptions | undefined | null)
  getUpdate(options?: UpdaterGetUpdateOptions | undefined | null): Promise<Update | null>
  download(bundleUpdates: Array<BundleUpdate>, options?: UpdaterDownloadOptions | undefined | null, cancellation?: Cancellation | undefined | null): Promise<UpdaterDownloadResult[]>
  install(targets: Array<UpdaterInstallTarget>): Promise<UpdaterInstallResult[]>
  rollback(targets: Array<UpdaterRollbackTarget>): Promise<UpdaterRollbackResult[]>
}

/**
 * Options for building a bundle.
 *
 * @property {HeaderWriterOptions} [header] - Header generation options
 * @property {IndexWriterOptions} [index] - Index generation options
 * @property {ChecksumWriteOptions} [dataChecksum] - Checksum generation for the data section
 */
export interface BundleBuilderOptions {
  header?: HeaderWriterOptions
  index?: IndexWriterOptions
  dataChecksum?: ChecksumWriteOptions
}

/**
 * Options for the bundle protocol.
 *
 * @property {UriBundleResolver} [bundleResolver] - How the bundle name is resolved (default: first hostname segment)
 * @property {UriPathResolver} [pathResolver] - How the file path is resolved (default: 'directory_index')
 */
export interface BundleProtocolOptions {
  bundleResolver?: UriBundleResolver
  pathResolver?: UriPathResolver
}

export interface BundleSourceVersion {
  source: SourceKind
  version: string
}

export interface BundleUpdate {
  name: string
  version: string
  downloadUrl?: string
  integrity?: string
  metadata?: Record<string, string>
}

/**
 * Checksum verification for the data section.
 *
 * @property {boolean} [verify] - Verify the section's xxHash-32 checksum on read (default: true)
 * @property {number} [seed] - Seed the checksum was built with (default: 0)
 */
export interface ChecksumReadOptions {
  verify?: boolean
  seed?: number
}

/**
 * Checksum generation for a bundle section.
 *
 * @property {number} [seed] - Seed the checksum is built with (default: 0)
 */
export interface ChecksumWriteOptions {
  seed?: number
}

/**
 * Computes the integrity of `data` with `algorithm`.
 *
 * This is the write side of integrity: use it when publishing a bundle to produce the
 * string a source or updater later verifies against.
 *
 * @param {IntegrityAlgorithm} algorithm - Hash algorithm to digest with
 * @param {Buffer} data - Bytes to digest
 * @returns {Integrity} The computed integrity
 *
 * @example
 * ```typescript
 * import { computeIntegrity } from '@wvb/node';
 *
 * const integrity = computeIntegrity('sha256', data).serialize();
 * // "sha256:n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg="
 * ```
 */
export declare function computeIntegrity(algorithm: IntegrityAlgorithm, data: Buffer): Integrity

/**
 * How entry data is read out of a bundle's data section.
 *
 * @property {ChecksumReadOptions} [checksum] - Checksum verification for the data section
 */
export interface DataReadOptions {
  checksum?: ChecksumReadOptions
}

/** The stable code every error thrown by this binding carries (`WebviewBundleError.code`). */
export type ErrorCode =  'core.io'|
'core.compress'|
'core.decompress'|
'core.encode'|
'core.decode'|
'core.http'|
'core.http_invalid_uri'|
'core.cancelled'|
'core.timeout'|
'core.invalid_magic_num'|
'core.invalid_version'|
'core.invalid_header_checksum'|
'core.invalid_index_checksum'|
'core.checksum_mismatch'|
'core.bundle_not_found'|
'core.invalid_filepath'|
'core.serde_json'|
'core.cannot_resolve_proxy_server'|
'core.http_client'|
'core.remote_http'|
'core.bad_remote_response'|
'core.invalid_remote_config'|
'core.invalid_updater_config'|
'core.invalid_integrity'|
'core.integrity_required'|
'core.integrity_verify_failed'|
'core.invalid_signature'|
'core.invalid_signature_key'|
'core.expect_signature_not_found'|
'core.signature_verify_failed'|
'core.generic'|
'invalid_header_name'|
'invalid_header_value'|
'invalid_signature_key'|
'napi';

export const EXTENSION: string

/**
 * How a bundle's header is read.
 *
 * @property {ChecksumReadOptions} [checksum] - Checksum verification for the header section
 */
export interface HeaderReadOptions {
  checksum?: ChecksumReadOptions
}

/**
 * Options for bundle header generation.
 *
 * @property {ChecksumWriteOptions} [checksum] - Checksum generation for the header section
 */
export interface HeaderWriterOptions {
  checksum?: ChecksumWriteOptions
}

/**
 * Which hostname segment is used as the bundle name.
 *
 * A number can be given instead to pick the nth segment (0-based).
 *
 * @enum {string}
 */
export type HostnameSegment = /** First segment. (e.g. `app.mydomain.com` -> `app`) */
'first'|
/** Full hostname. (e.g. `app.wvb` -> `app.wvb`) */
'full'|
/** Strip the last segment. (e.g. `a.b.wvb` -> `a.b`) */
'strip_suffix';

export type HttpMethod =  'get'|
'head'|
'options'|
'post'|
'put'|
'patch'|
'delete'|
'trace'|
'connect';

export interface HttpOptions {
  defaultHeaders?: Record<string, string>
  userAgent?: string
  timeout?: number
  readTimeout?: number
  connectTimeout?: number
  poolIdleTimeout?: number
  poolMaxIdlePerHost?: number
  referer?: boolean
  tcpNodelay?: boolean
}

export interface HttpResponse {
  status: number
  headers: Record<string, string>
  body: Buffer
}

/**
 * Metadata for a single file in the bundle.
 *
 * Contains information about file location, size, MIME type, and HTTP headers.
 *
 * @property {number} offset - Byte offset in the data section (compressed)
 * @property {number} len - Length of compressed data in bytes
 * @property {boolean} isEmpty - Whether the compressed data is empty
 * @property {string} contentType - MIME type of the file
 * @property {number} contentLength - Original file size before compression
 * @property {Record<string, string>} headers - HTTP headers for this file
 */
export interface IndexEntry {
  offset: number
  len: number
  isEmpty: boolean
  contentType: string
  contentLength: number
  headers: Record<string, string>
}

/**
 * How a bundle's index is read.
 *
 * @property {ChecksumReadOptions} [checksum] - Checksum verification for the index section
 */
export interface IndexReadOptions {
  checksum?: ChecksumReadOptions
}

/**
 * Options for bundle index generation.
 *
 * @property {ChecksumWriteOptions} [checksum] - Checksum generation for the index section
 */
export interface IndexWriterOptions {
  checksum?: ChecksumWriteOptions
}

/**
 * Hash algorithm for bundle integrity verification.
 *
 * Supports SHA-2 family hash algorithms for cryptographic verification.
 *
 * @example
 * ```typescript
 * // Integrity strings are `<algorithm>:<base64>`:
 * // "sha256:abc123..." - SHA-256
 * // "sha384:def456..." - SHA-384 (recommended)
 * // "sha512:ghi789..." - SHA-512
 * ```
 */
export type IntegrityAlgorithm = /** SHA-256 (256-bit hash) */
'sha256'|
/** SHA-384 (384-bit hash| recommended) */
'sha384'|
/** SHA-512 (512-bit hash) */
'sha512';

/**
 * Policy for enforcing integrity verification during bundle operations.
 *
 * Controls when integrity hashes are required and how missing hashes are handled.
 */
export type IntegrityPolicy = /** Require integrity verification for all bundles. Operations fail if integrity is missing or invalid. */
'strict'|
/** Verify integrity if provided| but allow operations without it. */
'optional'|
/** Skip integrity verification entirely. */
'off';

export interface ManifestBundleItem {
  name: string
  version: string
  status: ManifestBundleItemStatus
  data: ManifestVersionData
}

export type ManifestBundleItemStatus =  'current'|
'previous'|
'staged'|
'orphan';

export interface ManifestBundleSet {
  versions: Record<string, ManifestVersionData>
  currentVersion?: string
  previousVersion?: string
  stagedVersion?: string
}

export interface ManifestData {
  manifestVersion: ManifestVersion
  bundles: Record<string, ManifestBundleSet>
}

export interface ManifestPruneResult {
  name: string
  prunedVersions: Array<string>
}

export interface ManifestRemoveData {
  versions: Array<string>
  force?: boolean
}

export interface ManifestRemoveResult {
  name: string
  version: string
  kind: ManifestRemoveResultKind
}

export type ManifestRemoveResultKind =  'removed'|
'not_exists'|
'version_not_exists'|
'in_use';

export interface ManifestSetCurrentVersionResult {
  name: string
  version: string
  kind: ManifestSetCurrentVersionResultKind
}

export type ManifestSetCurrentVersionResultKind =  'settled'|
'not_exists'|
'version_not_exists';

export interface ManifestStageData {
  version: string
  data?: ManifestVersionData
}

export interface ManifestStageResult {
  name: string
  version: string
  kind: ManifestStageResultKind
}

export type ManifestStageResultKind =  'staged'|
'in_use';

export declare enum ManifestVersion {
  V1 = 1
}

export interface ManifestVersionData {
  integrity?: string
  metadata?: Record<string, string>
}

export const MIME_TYPE: string

/**
 * Parses a serialized integrity string (e.g. `"sha256:n4bQ..."`).
 *
 * @param {string} integrity - Serialized `<algorithm>:<base64>` string
 * @returns {Integrity} The parsed integrity
 *
 * @example
 * ```typescript
 * import { parseIntegrity } from '@wvb/node';
 *
 * const isValid = parseIntegrity(advertised).validate(data);
 * ```
 */
export declare function parseIntegrity(integrity: string): Integrity

/**
 * Reads a bundle from a file asynchronously.
 *
 * @param {string} filepath - Path to the `.wvb` file
 * @returns {Promise<Bundle>} Parsed bundle
 * @throws {Error} If the file cannot be read or is not a valid bundle
 *
 * @example
 * ```typescript
 * const bundle = await readBundle('app.wvb');
 * const html = bundle.getData('/index.html');
 * ```
 */
export declare function readBundle(filepath: string): Promise<Bundle>

/**
 * Reads a bundle from a buffer synchronously.
 *
 * @param {Buffer} buffer - Buffer containing bundle data
 * @returns {Bundle} Parsed bundle
 * @throws {Error} If the buffer is not a valid bundle
 *
 * @example
 * ```typescript
 * import { readFileSync } from 'fs';
 * const buffer = readFileSync('app.wvb');
 * const bundle = readBundleFromBuffer(buffer);
 * ```
 */
export declare function readBundleFromBuffer(buffer: Buffer): Bundle

export interface RemoteConfig {
  baseUrl: string
  http?: HttpOptions
  onDownload?: (data: RemoteOnDownloadData) => void
}

export interface RemoteGetUpdateOptions {
  etag?: string
  channel?: string
  expectSignature?: SignatureVerifyKey
}

/**
 * Download progress data.
 *
 * @property {number} downloadedBytes - Bytes downloaded so far
 * @property {number} totalBytes - Total bytes to download
 * @property {string} url - URL being downloaded from
 */
export interface RemoteOnDownloadData {
  downloadedBytes: number
  totalBytes?: number
  url: string
}

export interface RemoteUpdateResponse {
  update: Update
  etag?: string
  signature?: UpdateSignature
}

export const RUNTIME_VERSION: number

/**
 * Digital signature algorithm for bundle verification.
 *
 * Supports multiple signature schemes for cryptographic verification of bundle authenticity.
 */
export type SignatureAlgorithm = /** RSA PKCS#1 v1.5 signature scheme */
'rsa-pkcs1-v1_5-sha256'|
/** RSA-PSS (Probabilistic Signature Scheme) */
'rsa-pss-sha256'|
/** ECDSA with P-256 curve (secp256r1) */
'ecdsa-secp256r1'|
/** ECDSA with P-384 curve (secp384r1) */
'ecdsa-secp384r1'|
/** Ed25519 */
'ed25519';

/**
 * Configuration for signature verification.
 *
 * @property {SignatureAlgorithm} algorithm - The signature algorithm to use
 * @property {SignatureKeyData} key - The public key configuration
 */
export interface SignatureKey {
  algorithm: SignatureAlgorithm
  key: SignatureKeyData
}

/**
 * Public key configuration for signature verification.
 *
 * @property {VerifyingKeyFormat} format - The format of the public key
 * @property {string | Uint8Array} data - The key data (string for PEM, Uint8Array for DER/Raw)
 */
export interface SignatureKeyData {
  format: SignatureKeyFormat
  data: string | Uint8Array
}

/**
 * Format of the public key used for signature verification.
 *
 * Different algorithms support different key formats.
 *
 * @example
 * ```typescript
 * import fs from 'fs';
 *
 * // PEM format (text)
 * const pemKey = fs.readFileSync('./public-key.pem', 'utf8');
 * const config1 = {
 *   format: 'spki_pem',
 *   data: pemKey,
 * };
 *
 * // DER format (binary)
 * const derKey = fs.readFileSync('./public-key.der');
 * const config2 = {
 *   format: 'spki_der',
 *   data: derKey,
 * };
 *
 * // Raw bytes (Ed25519 only)
 * const rawKey = new Uint8Array(32);
 * const config3 = {
 *   format: 'raw',
 *   data: rawKey,
 * };
 * ```
 */
export type SignatureKeyFormat = /** SubjectPublicKeyInfo DER format (binary) */
'spki_der'|
/** SubjectPublicKeyInfo PEM format (text) */
'spki_pem'|
/** PKCS#1 DER format (RSA only| binary) */
'pkcs1_der'|
/** PKCS#1 PEM format (RSA only| text) */
'pkcs1_pem'|
/** SEC1 format (ECDSA only| binary) */
'sec1'|
/** Raw key bytes (Ed25519 only| 32 bytes) */
'raw';

export interface SignatureVerifyKey {
  id: string
  verify: SignatureKey | ((message: Uint8Array, signature: string) => Promise<boolean>)
}

export interface SourceConfig {
  builtinDir: string
  remoteDir: string
  builtinManifestFilepath?: string
  remoteManifestFilepath?: string
  options?: SourceOptions
}

export type SourceIntegrityCheckMode =  'all'|
'only_remote';

export interface SourceIntegrityOptions {
  policy?: IntegrityPolicy
  checkMode?: SourceIntegrityCheckMode
}

export type SourceKind =  'builtin'|
'remote';

export interface SourceListItem {
  source: SourceKind
  item: ManifestBundleItem
}

export interface SourceOptions {
  headerRead?: HeaderReadOptions
  indexRead?: IndexReadOptions
  dataRead?: DataReadOptions
  integrity?: SourceIntegrityOptions
  removeBundleChunkSize?: number
}

export interface Update {
  id: string
  createdAt: string
  runtimeVersion: number
  bundles: Array<BundleUpdate>
  metadata: Record<string, string>
}

export const UPDATE_PROTOCOL_VERSION: string

export interface UpdaterDownloadOptions {
  concurrency?: number
  timeout?: number
}

export interface UpdaterDownloadResult {
  name: string
  version: string
  integrity?: string
  metadata?: Record<string, string>
  result: UpdaterDownloadResultKind
}

export type UpdaterDownloadResultKind =
  | { type: 'downloaded' }
  | { type: 'error', code: ErrorCode, message: string }

export interface UpdaterGetUpdateOptions {
  expectSignatureKeyId?: string
}

export interface UpdaterInstallResult {
  name: string
  targetVersion?: string
  installVersion?: string
  result: UpdaterInstallResultKind
}

export type UpdaterInstallResultKind =
  | { type: 'installed' }
  | { type: 'staged_version_not_matched' }
  | { type: 'staged_bundle_not_exists' }
  | { type: 'verify_failed' }
  | { type: 'error', code: ErrorCode, message: string }

export interface UpdaterInstallTarget {
  name: string
  version?: string
}

export interface UpdaterIntegrityOptions {
  policy?: IntegrityPolicy
  algorithm?: IntegrityAlgorithm
}

export interface UpdaterOptions {
  channel?: string
  integrity?: UpdaterIntegrityOptions
  signature?: UpdaterSignatureOptions
}

export interface UpdaterRollbackResult {
  name: string
  targetVersion?: string
  rollbackVersion?: string
  result: UpdaterRollbackResultKind
}

export type UpdaterRollbackResultKind =
  | { type: 'rolled_back' }
  | { type: 'previous_version_not_matched' }
  | { type: 'previous_bundle_not_exists' }
  | { type: 'verify_failed' }
  | { type: 'group_failed', groups: Array<string> }
  | { type: 'error', code: ErrorCode, message: string }

export interface UpdaterRollbackTarget {
  name: string
  version?: string
}

export interface UpdaterSignatureOptions {
  keys?: Array<SignatureVerifyKey>
}

export interface UpdateSignature {
  keyId: string
  sig: string
  alg: string
}

/**
 * Options for resolving the bundle name from the request uri.
 *
 * - `hostname`: from the uri hostname.
 *   - `segment` - Hostname segment to use, or the nth segment (default: 'first')
 *   - `allowWvbSuffixOnly` - Only resolve hosts ending in `.wvb` (default: false)
 * - `pathname`: from the uri pathname.
 *   - `segmentIndex` - Path segment index, 0-based over non-empty segments (default: 0)
 *
 * @example
 * ```typescript
 * // `https://app.wvb/index.html` -> bundle "app"
 * const byHostname: UriBundleResolver = { type: 'hostname' };
 *
 * // `https://cdn.example.com/my-app/index.html` -> bundle "my-app"
 * const byPathname: UriBundleResolver = { type: 'pathname', segmentIndex: 0 };
 * ```
 */
export type UriBundleResolver =
  | { type: 'hostname', segment?: HostnameSegment | number, allowWvbSuffixOnly?: boolean }
  | { type: 'pathname', segmentIndex?: number }

/**
 * How the file path in the bundle is resolved from the request uri.
 *
 * @enum {string}
 */
export type UriPathResolver = /** Use the uri path as-is (only percent-decoded). */
'exact'|
/**
 * Directory index: `/` -> `/index.html` and `/about` -> `/about/index.html`.
 * (static-site / MPA style; e.g. Astro `format: 'directory'` / Next `trailingSlash: true`)
 */
'directory_index'|
/**
 * `.html` extension: `/` -> `/index.html` and `/about` -> `/about.html`.
 * (flat-file style; e.g. Astro `format: 'file'` / GitHub Pages / Next `trailingSlash: false`)
 */
'html_extension';

export type Version =  'v1';

/**
 * Writes a bundle to a file asynchronously.
 *
 * @param {Bundle} bundle - Bundle to write
 * @param {string} filepath - Destination file path
 * @returns {Promise<number>} Number of bytes written
 * @throws {Error} If the file cannot be written
 *
 * @example
 * ```typescript
 * const builder = new BundleBuilder();
 * builder.insertEntry('/index.html', Buffer.from('<html></html>'));
 * const bundle = builder.build();
 * await writeBundle(bundle, 'output.wvb');
 * ```
 */
export declare function writeBundle(bundle: Bundle, filepath: string): Promise<bigint>

/**
 * Writes a bundle to a buffer synchronously.
 *
 * @param {Bundle} bundle - Bundle to write
 * @returns {Buffer} Bundle data as a buffer
 *
 * @example
 * ```typescript
 * const bundle = builder.build();
 * const buffer = writeBundleIntoBuffer(bundle);
 * console.log(`Bundle size: ${buffer.length} bytes`);
 * ```
 */
export declare function writeBundleIntoBuffer(bundle: Bundle): Buffer
