// @generated from `src/error_codes.rs` by `build.rs` — do not edit.

/** The stable code every {@link WebviewBundleError} carries. */
export type ErrorCode =
  | 'core.io'
  | 'core.compress'
  | 'core.decompress'
  | 'core.encode'
  | 'core.decode'
  | 'core.http'
  | 'core.invalid_magic_num'
  | 'core.invalid_version'
  | 'core.invalid_header_checksum'
  | 'core.invalid_index_checksum'
  | 'core.checksum_mismatch'
  | 'core.bundle_not_found'
  | 'core.bundle_entry_not_exists'
  | 'core.bundle_cannot_be_removed'
  | 'core.invalid_filepath'
  | 'core.serde_json'
  | 'core.cannot_resolve_proxy_server'
  | 'core.reqwest'
  | 'core.invalid_remote_url'
  | 'core.invalid_remote_bundle'
  | 'core.remote_bundle_not_found'
  | 'core.remote_forbidden'
  | 'core.remote_http'
  | 'core.invalid_remote_config'
  | 'core.invalid_integrity'
  | 'core.integrity_required'
  | 'core.integrity_verify_failed'
  | 'core.invalid_signature'
  | 'core.invalid_signing_key'
  | 'core.signature_sign_failed'
  | 'core.invalid_verifying_key'
  | 'core.signature_not_exists'
  | 'core.signature_verify_failed'
  | 'core.generic'
  | 'invalid_method'
  | 'invalid_request'
  | 'invalid_signature_options'
  | 'null_handle'
  | 'unknown';
