// @generated from `src/error_codes.rs` by `build.rs` — do not edit.

/** The stable code every {@link WebviewBundleError} carries. */
export type ErrorCode =
  | 'core.io'
  | 'core.compress'
  | 'core.decompress'
  | 'core.encode'
  | 'core.decode'
  | 'core.http'
  | 'core.http_invalid_uri'
  | 'core.cancelled'
  | 'core.timeout'
  | 'core.invalid_magic_num'
  | 'core.invalid_version'
  | 'core.invalid_header_checksum'
  | 'core.invalid_index_checksum'
  | 'core.checksum_mismatch'
  | 'core.bundle_not_found'
  | 'core.invalid_filepath'
  | 'core.serde_json'
  | 'core.cannot_resolve_proxy_server'
  | 'core.http_client'
  | 'core.remote_http'
  | 'core.bad_remote_response'
  | 'core.invalid_remote_config'
  | 'core.invalid_updater_config'
  | 'core.invalid_integrity'
  | 'core.integrity_required'
  | 'core.integrity_verify_failed'
  | 'core.invalid_signature'
  | 'core.invalid_signature_key'
  | 'core.expect_signature_not_found'
  | 'core.signature_verify_failed'
  | 'core.generic'
  | 'invalid_method'
  | 'invalid_request'
  | 'invalid_signature_key'
  | 'null_handle'
  | 'unknown';
