name: "node setup"
description: "node setup"
runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # 3.5.1
      with:
        install_args: "node"
    - run: |
        corepack enable
        corepack prepare --activate
      shell: bash
    - id: yarn-cache-dir
      run: echo "YARN_CACHE_DIR=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # 5.0.3
      with:
        path: ${{ steps.yarn-cache-dir.outputs.YARN_CACHE_DIR }}
        key: ${{ runner.os }}-node-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-yarn-
